"""
OMNeT++ Network Configuration Generator

This script reads a JSON configuration file generated by the AFDX simulator
and produces two OMNeT++ files:
1. .ned file: Defines the network topology with submodules and connections
2. .ini file: Configures traffic parameters, routing tables, and switch settings
"""

from collections import defaultdict
import json
from math import lcm


def lire_json(fichier_json):
    """
    Reads a JSON configuration file and returns its content as a dictionary
    """
    with open(fichier_json, 'r') as f:
        return json.load(f)


#----- .NED FILE GENERATION -------

def cree_fichier_ned(config, fichier_sortie="/home/zakarya/omnetpp-workspace/simulation_exemple/simulations/reseauFifo.ned"):
    """
    Generates a .ned file defining the network topology for OMNeT++
    
    The NED file contains:
    - AfdxSource modules (end systems that send traffic)
    - AfdxSink modules (end systems that receive traffic)
    - AfdxSwitch modules (network switches)
    - Connections between modules (links)
    
    """
    end_systems = config["end_systems"]
    switches    = config["switches"]

    # ---- Automatic Positioning ----
    x_src  = 80      # Source X position (left side)
    x_dst  = 700     # Destination X position (right side)
    x_sw0  = 250     # First switch X position
    dx_sw  = 150     # Spacing between switches
    y_step = 80      # Vertical spacing between end system
    y_base = 80      # Starting Y position


    # ---- Start NED File Content ----
    contenu_ned = """
import simulation_exemple.AfdxSource;
import simulation_exemple.AfdxSwitch;
import simulation_exemple.AfdxSink;

network AfdxNetwork
{
    @display("bgb=900,600");
    submodules:
"""

    #Sources: end systems with an output port destination 
    src_list = [es for es in end_systems
                if es["output_port"]["destination"] is not None]

    #Destinations: end systems with no output port destination 
    dst_list = [es for es in end_systems
                if es["output_port"]["destination"] is None]

    #Add Source Modules 
    for i, es in enumerate(src_list):
        y = y_base + i * y_step
        contenu_ned += f"""
        {es["id"]}: AfdxSource {{
            @display("p={x_src},{y}");
        }}"""

    #Add Destination Modules
    for i, es in enumerate(dst_list):
        y = y_base + i * y_step
        contenu_ned += f"""
        {es["id"]}: AfdxSink {{
            @display("p={x_dst},{y}");
        }}"""

    #Add Switch Modules
    for i, sw in enumerate(switches):
        x = x_sw0 + i * dx_sw
        #Number of input ports
        num_in  = len(sw["input_port"])
        #Number of output ports
        num_out = get_num_out(sw["output_port"])
        contenu_ned += f"""
        {sw["id"]}: AfdxSwitch {{
            numIn  = {num_in};
            numOut = {num_out};
            @display("p={x},300");
        }}"""

    #Add Connections 
    contenu_ned += """
    connections:
"""
    #Connection Type 1: End System → Switch
    for sw in switches:
        for i, es_id in enumerate(sw["input_port"]):
            #Only for end systems
            if es_id.startswith("ES"):
                contenu_ned += f"""
        {es_id}.out --> {sw["id"]}.in[{i}];"""

    #Connection Type 2: Switch → End System or Switch → Switch
    for sw in switches:
        for i, port in enumerate(sw["output_port"]):
            dest = port["destination"]
            #Skip ports with no destination
            if dest is None:
                continue
            #Switch → End System connection
            if dest.startswith("ES"):
                contenu_ned += f"""
        {sw["id"]}.out[{i}] --> {dest}.in;"""
            
            #Switch → Switch connection
            elif dest.startswith("SW"):
                sw_dest = next((s for s in switches if s["id"] == dest), None)
                if sw_dest is None:
                    continue
                try:
                    #Find the input port index on the destination switch
                    idx_in = sw_dest["input_port"].index(sw["id"])
                    contenu_ned += f"""
        {sw["id"]}.out[{i}] --> {dest}.in[{idx_in}];"""
                except ValueError:
                    #If index not found, use dynamic port assignment
                    contenu_ned += f"""
        {sw["id"]}.out[{i}] --> {dest}.in++;"""

    #Close the network definition
    contenu_ned += "\n}\n"


    #Write the .ned File
    with open(fichier_sortie, 'w') as f:
        f.write(contenu_ned)

    print(f"[NED]  File generated: {fichier_sortie}")
    return fichier_sortie



# ---- .INI FILE GENERATION ----
def cree_fichier_ini(config, fichier_sortie="/home/zakarya/omnetpp-workspace/simulation_exemple/simulations/omnetpp.ini"):
    """
    Generates an .ini configuration file for OMNeT++ simulation.
    
    The INI file contains:
    - Source configurations (VLs, BAG, frame size, priority)
    - Switch configurations (link speed, priority levels, routing tables)
    - Sink configurations
    """
    switches = config["switches"]
    flux     = config["Flow"]

    #General Simulation Settings
    sim_time_limit = 10#2*lcm(flux["bag_us"])
    contenu_ini = """[General]
network = AfdxNetwork
sim-time-limit =""" + str(sim_time_limit) + """s"""


    #Source Configuration
    contenu_ini += "\n# Configuration des sources AFDX\n"

    #Group flows by their source end system
    flux_par_source = defaultdict(list)
    for f in flux:
        flux_par_source[f["source"]].append(f)

    #Track all priorities for max priority calculation
    priorites = []

    for source, flux_es in flux_par_source.items():
        #Number of Virtual Links for this source
        num_vls = len(flux_es)
        contenu_ini += f"\n*.{source}.numVLs = {num_vls}\n"

        #Build VL configuration string: "bag:size:vl_id:priority"
        parts = []
        for f in flux_es:
            bag_s  = f["bag"] / 1_000_000.0   #Convert microseconds to seconds
            taille = f["size"]
            vl_id  = f["id"].replace("V", "")    #Extract numeric VL ID
            prio   = f["priority"]
            priorites.append(prio)
            parts.append(f"{bag_s}:{taille}:{vl_id}:{prio}")

        #Join multiple VLs with '|' separator
        vls_config = "|".join(parts)
        contenu_ini += f'*.{source}.vls_config = "{vls_config}"\n'

    #Switch Configuration 
    contenu_ini += "\n# AFDX Switch Configuration\n"
    #Calculate the maximum priority level (0 = highest)
    priorite_max = (max(priorites) + 1) if priorites else 1

    for sw in switches:
        sw_id = sw["id"]

        #Basic switch parameters
        contenu_ini += f"""
*.{sw_id}.debitLienMbps = 100
*.{sw_id}.numPriorite   = {priorite_max}
"""

        #Routing Table Configuration
        routing_entries = []
        for f in flux:
            path   = f["path"]
            #Skip flows with no valid path
            if path is None:
                continue

            vl_id    = f["id"].replace("V", "")
            priorite = f["priority"]

            #If this switch is on the flow's path, find the next hop
            if sw_id in path:
                idx = path.index(sw_id)
                if idx + 1 < len(path):
                    next_hop = path[idx + 1]

                    #Find the output port for the next hop
                    out_port = None
                    for k, port in enumerate(sw["output_port"]):
                        if port["destination"] == next_hop:
                            out_port = k
                            break
                    if out_port is not None:
                        routing_entries.append(f"VL{vl_id}:{out_port},{priorite}")
        
        #Format routing table: "VL1:2,3; VL2:1,2"
        if routing_entries:
            routing_table_str = "; ".join(routing_entries)
            contenu_ini += f'*.{sw_id}.routingTable = "{routing_table_str}"\n'
        else:
            contenu_ini += f'*.{sw_id}.routingTable = ""\n'

    #Sink Configuration 
    contenu_ini += "\n# AFDX Sink Configuration\n"
    destinations = set(f["destination"] for f in flux)
    sources_set  = set(f["source"]      for f in flux)
    for dest in destinations:
        if dest not in sources_set:
            #Destinations that are not also sources get automatic positioning
            contenu_ini += f'*.{dest}.displayString = "p=auto"\n'

    #Write the .ini File
    with open(fichier_sortie, 'w') as f:
        f.write(contenu_ini)

    print(f"[INI] File generated : {fichier_sortie}")
    return fichier_sortie


def get_num_out(port_sortie):
    """
    Helper function to get the number of output ports on a switch
    """
    if isinstance(port_sortie, list):
        return len(port_sortie)
    return 1


def main():
    fichier_json = 'Generator_Output.json'
    config = lire_json(fichier_json)
    cree_fichier_ned(config)
    cree_fichier_ini(config)
    print("OMNeT++ configuration files generated successfully!")

if __name__ == "__main__":
    main()